apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:latest
          env:
            - name: DB_HOST
              value: postgres.local
            - name: DB_PORT
              value: "30007"
            - name: DB_NAME
              value: gitlab-db
            - name: DB_USER
              value: gitlab
            - name: DB_PASSWORD
              value: gitlab
            - name: GITLAB_ROOT_PASSWORD
              value: MfhgfhfSSd123
            - name: GITLAB_ROOT_EMAIL
              value: tankouantchancthou@gmail.com
          resources:
            limits:
              cpu: "5"
              memory: "10Gi"
            requests:
              cpu: "4"
              memory: "5Gi"
          volumeMounts:
            - mountPath: /etc/gitlab
              name: cache-volume
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: pvc-gitlab