apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:nightly
          env:
            - name: GITLAB_ROOT_PASSWORD
              value: MyPassword123
            - name: GITLAB_ROOT_EMAIL
              value: tankouantchancthou@gmail.com
          resources:
            limits:
              cpu: "4"
              memory: "7Gi"
            requests:
              cpu: "3"
              memory: "5Gi"
          volumeMounts:
            - mountPath: /var/opt/gitlab
              name: cache-volume
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: pvc-gitlab