apiVersion: v1
kind: Pod
metadata:
  name: gitlab
spec:
  containers:
    - name: gitlab
      image: gitlab/gitlab-ce:16.2.8-ce.0
      env:
        - name: DB_HOST
          value: 192.168.8.102
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: gitlab
        - name: DB_USER
          value: utilisateur-base-de-donnees
        - name: postgres
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres