apiVersion: v1
kind: Pod
metadata:
  name: client-posgres
spec:
  containers:
    - name: client-posgres-container
      image: postgres:15
      env:
        - name: POSTGRES_USER
          value: postgres-test
        - name: POSTGRES_PASSWORD
          value: postgres-test
