apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv_gitlab
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: medium
  hostPath:
    path: C:\\tools