apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: hostpath
  selector:
    matchLabels:
      type: local