apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc_gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: medium
  volumeName: pv_gitlab